# Generated by Django 5.0.6 on 2026-07-09 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('code', models.CharField(help_text='e.g., crm, erp', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('TENANT_SPECIFIC', 'Tenant Specific')], default='PRIVATE', max_length=32)),
                ('logo', models.URLField(blank=True, max_length=1024)),
                ('banner', models.URLField(blank=True, max_length=1024)),
                ('icon', models.URLField(blank=True, max_length=1024)),
                ('website', models.URLField(blank=True, max_length=1024)),
                ('documentation_url', models.URLField(blank=True, max_length=1024)),
                ('support_url', models.URLField(blank=True, max_length=1024)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('pricing_model', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'marketplace_products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'marketplace_categories',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_listings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('environment_variables', models.JSONField(blank=True, default=dict)),
                ('database_requirements', models.JSONField(blank=True, default=dict)),
                ('redis_requirements', models.JSONField(blank=True, default=dict)),
                ('memory_req', models.CharField(blank=True, max_length=50)),
                ('cpu_req', models.CharField(blank=True, max_length=50)),
                ('disk_req', models.CharField(blank=True, max_length=50)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_product_configurations',
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('version_number', models.CharField(help_text='e.g., 1.2.0', max_length=50)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True)),
                ('min_platform_version', models.CharField(blank=True, max_length=50)),
                ('max_platform_version', models.CharField(blank=True, max_length=50)),
                ('docker_image', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('download_url', models.URLField(blank=True, max_length=1024)),
                ('size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('is_stable', models.BooleanField(default=True)),
                ('is_lts', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_product_versions',
                'unique_together': {('product', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('version_requirement', models.CharField(blank=True, help_text='e.g., >=1.0.0', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='marketplace.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_product_dependencies',
                'unique_together': {('product', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='TenantProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('auto_update', models.BooleanField(default=False)),
                ('is_installed', models.BooleanField(default=False)),
                ('deployment_status', models.CharField(blank=True, help_text='Status for Layer 6 communication', max_length=32)),
                ('deployment_id', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.productversion')),
            ],
            options={
                'db_table': 'marketplace_tenant_products',
                'unique_together': {('tenant', 'product')},
            },
        ),
    ]
