# Generated by Django 5.0.6 on 2026-07-12 11:35

import apps.marketplace.models.application
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('code', models.CharField(help_text='Unique identifier, e.g., gitlab, redis', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=32)),
            ],
            options={
                'db_table': 'marketplace_applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('version_number', models.CharField(help_text='e.g., 1.0.0', max_length=50)),
                ('image_ref', models.CharField(help_text='e.g., localhost:5000/myapp:v1', max_length=255)),
                ('manifest', models.JSONField(default=dict, help_text='JSON schema defining env_schema, runtime, resources', validators=[apps.marketplace.models.application.validate_manifest])),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketplace.application')),
            ],
            options={
                'db_table': 'marketplace_application_versions',
                'unique_together': {('application', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='TenantInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=32)),
                ('route_path', models.CharField(blank=True, help_text='Traefik routing path e.g., /tenant-a/app', max_length=255)),
                ('config_overrides', models.JSONField(blank=True, default=dict, help_text='Tenant specific environment values')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='tenants.tenant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='installations', to='marketplace.applicationversion')),
            ],
            options={
                'db_table': 'marketplace_tenant_installations',
            },
        ),
    ]
