# Generated by Django 5.0.6 on 2026-07-09 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.JSONField(default=list)),
                ('time_window_seconds', models.IntegerField(default=300, help_text='Max time window between first and last event.')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='CRITICAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'siem_correlation_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('THRESHOLD', 'Threshold'), ('EXACT_MATCH', 'Exact Match'), ('ANOMALY', 'Anomaly')], default='THRESHOLD', max_length=50)),
                ('conditions', models.JSONField(default=dict)),
                ('threshold', models.IntegerField(default=1, help_text='Number of matches required to trigger an alert.')),
                ('time_window_seconds', models.IntegerField(default=0, help_text='Time window for threshold-based rules (0 for instant).')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'siem_detection_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
