# Generated by Django 5.0.6 on 2026-06-27 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to the user's profile picture.", verbose_name='Avatar URL')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone identifier, e.g. 'Asia/Kolkata'.", max_length=64, verbose_name='Timezone')),
                ('language', models.CharField(default='en', help_text="BCP 47 language tag, e.g. 'en', 'hi', 'ta'.", max_length=16, verbose_name='Language')),
                ('date_format', models.CharField(default='YYYY-MM-DD', help_text='Preferred date display format.', max_length=32, verbose_name='Date Format')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive transactional emails (login alerts, etc.).', verbose_name='Email Notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive browser/mobile push notifications.', verbose_name='Push Notifications')),
                ('marketing_emails', models.BooleanField(default=False, help_text='Opt-in to product news and promotional content.', verbose_name='Marketing Emails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'iam_user_profiles',
            },
        ),
    ]
