# Generated by Django 5.0.6 on 2026-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login Success'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('DEPLOYMENT_STARTED', 'Deployment Started'), ('DEPLOYMENT_FAILED', 'Deployment Failed'), ('DEPLOYMENT_SUCCESS', 'Deployment Success'), ('RBAC_DENIED', 'RBAC Denied'), ('PRODUCT_PUBLISHED', 'Product Published'), ('TENANT_CREATED', 'Tenant Created'), ('USER_CREATED', 'User Created'), ('SYSTEM_ALERT', 'System Alert')], db_index=True, max_length=50),
        ),
    ]
