# Generated by Django 5.0.6 on 2026-06-27 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, help_text='Denormalized email stored at event time. Preserved even if user is later deleted.', max_length=254, verbose_name='User Email (snapshot)')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('LOGOUT_ALL', 'Logout All Sessions'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('TOKEN_REVOKED', 'Token Revoked'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_USED', 'Password Reset Used'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('EMAIL_VERIFICATION_SENT', 'Verification Email Sent'), ('EMAIL_VERIFIED', 'Email Verified'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('MFA_VERIFIED', 'MFA Code Verified'), ('MFA_FAILED', 'MFA Verification Failed'), ('BACKUP_CODE_USED', 'Backup Code Used'), ('BACKUP_CODES_REGENERATED', 'Backup Codes Regenerated'), ('NEW_DEVICE_DETECTED', 'New Device Detected'), ('DEVICE_TRUSTED', 'Device Trusted'), ('DEVICE_REMOVED', 'Device Removed'), ('SESSION_CREATED', 'Session Created'), ('SESSION_EXPIRED', 'Session Expired'), ('SESSION_REVOKED', 'Session Revoked'), ('PROFILE_UPDATED', 'Profile Updated'), ('SERVICE_ACCOUNT_CREATED', 'Service Account Created'), ('SERVICE_ACCOUNT_REVOKED', 'Service Account Revoked')], db_index=True, max_length=48, verbose_name='Event Type')),
                ('success', models.BooleanField(db_index=True, default=True, help_text='False for failed attempts.', verbose_name='Success')),
                ('failure_reason', models.CharField(blank=True, help_text='Short code for why the event failed, e.g. INVALID_PASSWORD.', max_length=128, verbose_name='Failure Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_id', models.UUIDField(blank=True, null=True, verbose_name='Device ID')),
                ('location', models.CharField(blank=True, help_text='Approximate geo location.', max_length=128, verbose_name='Location')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event-specific structured context. e.g. {session_id, device_name, failed_count}', verbose_name='Metadata')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Populated by Layer 3 for tenant-scoped events.', null=True, verbose_name='Tenant ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Occurred At')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'db_table': 'iam_audit_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
