# Generated by Django 5.0.6 on 2026-06-27 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for events where user is unknown (e.g. failed login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'event_type'], name='idx_audit_user_event'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='idx_audit_type_date'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='idx_audit_ip_date'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant_id', 'created_at'], name='idx_audit_tenant_date'),
        ),
    ]
