# Generated by Django 5.0.6 on 2026-06-27 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "kavan-agent", "billing-daemon"', max_length=64, unique=True, verbose_name='Service Name')),
                ('api_key_hash', models.CharField(help_text='SHA-256 hash of the raw API key. Raw key shown once at creation.', max_length=64, unique=True, verbose_name='API Key Hash')),
                ('scopes', models.JSONField(default=list, help_text='e.g. ["audit:read", "session:revoke"]', verbose_name='Scopes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = no expiry.', null=True, verbose_name='Expires At')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Layer 3 hook.', null=True, verbose_name='Tenant ID')),
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
                'db_table': 'iam_service_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4). Never changes.', primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(db_index=True, help_text='Primary identifier used for login.', max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, db_index=True, help_text='Optional display name. Must be unique if set.', max_length=64, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, help_text='E.164 format preferred, e.g. +919876543210', max_length=20, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Email Verification'), ('VERIFIED', 'Email Verified — Awaiting Activation'), ('ACTIVE', 'Active'), ('LOCKED', 'Temporarily Locked'), ('SUSPENDED', 'Manually Suspended by Admin'), ('DISABLED', 'Permanently Disabled'), ('DELETED', 'Soft Deleted')], db_index=True, default='PENDING', help_text='User lifecycle state. See UserStatus enum.', max_length=16, verbose_name='Account Status')),
                ('email_verified', models.BooleanField(default=False, help_text='True when the user has clicked the verification link.', verbose_name='Email Verified')),
                ('is_active', models.BooleanField(default=True, help_text='False = account cannot log in. Prefer using `status` instead.', verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants Django admin access.', verbose_name='Is Staff')),
                ('mfa_enabled', models.BooleanField(default=False, help_text='True when TOTP MFA is active for this account.', verbose_name='MFA Enabled')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, help_text='Resets to 0 after successful login.', verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account is locked until this datetime. Null = not locked.', null=True, verbose_name='Locked Until')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful login.', null=True, verbose_name='Last Login At')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address used during the most recent login.', null=True, verbose_name='Last Login IP')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Populated by Layer 3. Null = platform-level user.', null=True, verbose_name='Tenant ID')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True, verbose_name='Created By')),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last modified this record.', null=True, verbose_name='Updated By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'iam_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the verification token.', max_length=64, unique=True, verbose_name='Token Hash')),
                ('email', models.EmailField(help_text='The email address being verified.', max_length=254, verbose_name='Email')),
                ('is_used', models.BooleanField(default=False, help_text='True once the user has consumed this token.', verbose_name='Is Used')),
                ('expires_at', models.DateTimeField(help_text='24 hours from creation time.', verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'db_table': 'iam_email_verifications',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the reset token.', max_length=64, unique=True, verbose_name='Token Hash')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('expires_at', models.DateTimeField(help_text='1 hour from creation time.', verbose_name='Expires At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Requested From IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'db_table': 'iam_password_resets',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw refresh token.', max_length=64, unique=True, verbose_name='Token Hash')),
                ('device_id', models.UUIDField(blank=True, help_text='References TrustedDevice if device is registered.', null=True, verbose_name='Device ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP from which this token was issued.', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='Is Revoked')),
                ('expires_at', models.DateTimeField(help_text='Absolute expiry — 30 days from issue time.', verbose_name='Expires At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'iam_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id'], name='idx_user_tenant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'is_used'], name='idx_ev_user_used'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['user', 'is_used'], name='idx_pr_user_used'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['expires_at'], name='idx_pr_expires'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'is_revoked'], name='idx_rt_user_active'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='idx_rt_expires'),
        ),
    ]
