# Generated by Django 5.0.6 on 2026-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_platform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_SUPPORT', 'Platform Support'), ('PLATFORM_OPERATOR', 'Platform Operator'), ('DEVOPS', 'DevOps'), ('SECURITY_ENGINEER', 'Security Engineer'), ('SECURITY_ANALYST', 'Security Analyst')], help_text='Internal KAVAN platform role. Null = standard tenant user.', max_length=32, null=True, verbose_name='Platform Role'),
        ),
    ]
