# Generated by Django 5.0.6 on 2026-06-27 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(help_text='Argon2 hash of the old password.', max_length=256, verbose_name='Password Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this password was set.', verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'db_table': 'iam_password_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
