# Generated by Django 5.0.6 on 2026-06-27 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, help_text='SHA-256 of (user_agent + accept_language + optional_client_fp). Unique per user+device pair.', max_length=64, verbose_name='Device Fingerprint')),
                ('device_name', models.CharField(blank=True, help_text="e.g. 'MacBook Pro', 'iPhone 15', 'Ubuntu Desktop'.", max_length=128, verbose_name='Device Name')),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('CLI', 'CLI / Script'), ('SERVICE', 'Service / API'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16, verbose_name='Device Type')),
                ('os', models.CharField(blank=True, help_text="e.g. 'macOS 14.1', 'Windows 11', 'Android 14'.", max_length=64, verbose_name='Operating System')),
                ('browser', models.CharField(blank=True, help_text="e.g. 'Chrome 126', 'Safari 17', 'Firefox 127'.", max_length=64, verbose_name='Browser')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Known IP')),
                ('is_trusted', models.BooleanField(db_index=True, default=False, help_text='Becomes True after user acknowledges the new device.', verbose_name='Is Trusted')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Updated on every login from this device.', null=True, verbose_name='Last Seen At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'iam_trusted_devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_trusted'], name='idx_device_user_trusted'), models.Index(fields=['device_fingerprint'], name='idx_device_fingerprint')],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
