# Generated by Django 5.0.6 on 2026-07-09 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('QUEUED', 'Queued'), ('VALIDATING', 'Validating'), ('PROVISIONING', 'Provisioning'), ('INSTALLING', 'Installing'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting'), ('HEALTH_CHECK', 'Health Check'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('ROLLBACK', 'Rollback'), ('ROLLED_BACK', 'Rolled Back')], default='REQUESTED', max_length=50)),
                ('version_tag', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='marketplace.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='tenants.tenant')),
                ('tenant_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer6_deployments', to='marketplace.tenantproduct')),
            ],
            options={
                'db_table': 'deployments_deployment',
            },
        ),
        migrations.CreateModel(
            name='DeploymentArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_url', models.URLField(max_length=1024)),
                ('artifact_type', models.CharField(blank=True, max_length=100)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_artifact',
            },
        ),
        migrations.CreateModel(
            name='DeploymentEnvironment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'deployments_environment',
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.deploymentenvironment'),
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_event',
            },
        ),
        migrations.CreateModel(
            name='DeploymentHealth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_healthy', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('metrics', models.JSONField(default=dict)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_health',
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_history',
            },
        ),
        migrations.CreateModel(
            name='DeploymentJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('QUEUED', 'Queued'), ('VALIDATING', 'Validating'), ('PROVISIONING', 'Provisioning'), ('INSTALLING', 'Installing'), ('CONFIGURING', 'Configuring'), ('STARTING', 'Starting'), ('HEALTH_CHECK', 'Health Check'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('ROLLBACK', 'Rollback'), ('ROLLED_BACK', 'Rolled Back')], default='QUEUED', max_length=50)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_job',
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_output', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deployments.deploymentjob')),
            ],
            options={
                'db_table': 'deployments_log',
            },
        ),
        migrations.CreateModel(
            name='DeploymentSecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('vault_path', models.CharField(blank=True, help_text='Path in HashiCorp Vault or similar', max_length=1024)),
                ('value_encrypted', models.TextField(blank=True, help_text='Encrypted secret value if stored directly')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_secret',
            },
        ),
        migrations.CreateModel(
            name='DeploymentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('docker_image', models.CharField(max_length=512)),
                ('helm_chart', models.CharField(blank=True, max_length=512)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_templates', to='marketplace.product')),
            ],
            options={
                'db_table': 'deployments_template',
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deployments.deploymenttemplate'),
        ),
        migrations.CreateModel(
            name='DeploymentVariable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='deployments.deployment')),
            ],
            options={
                'db_table': 'deployments_variable',
            },
        ),
    ]
