# Generated by Django 5.0.6 on 2026-07-09 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentartifact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentenvironment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentevent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymenthealth',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymenthistory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentjob',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentsecret',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymenttemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='deploymentvariable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentartifact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentenvironment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymenthealth',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymenthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentsecret',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymenttemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deploymentvariable',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
