# Generated by Django 5.0.6 on 2026-07-09 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIEMIntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('provider', models.CharField(choices=[('SPLUNK_HEC', 'Splunk HEC'), ('SENTINEL', 'Microsoft Sentinel'), ('WAZUH', 'Wazuh')], max_length=50, unique=True)),
                ('endpoint_url', models.URLField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('min_severity_to_forward', models.CharField(default='INFO', max_length=20)),
            ],
            options={
                'db_table': 'integrations_siem_config',
            },
        ),
        migrations.CreateModel(
            name='SIEMRetryQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('provider', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrations_siem_retry_queue',
                'ordering': ['next_retry_at'],
            },
        ),
    ]
