# Generated by Django 5.0.6 on 2026-07-09 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('tenant_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tenant_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('WARNING', 'Warning'), ('READ_ONLY', 'Read Only'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], db_index=True, default='PENDING', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('plan', models.CharField(max_length=50)),
                ('user_quota', models.IntegerField(default=10)),
                ('storage_quota_mb', models.IntegerField(default=1024)),
                ('api_quota', models.IntegerField(default=10000)),
                ('current_users', models.IntegerField(default=0)),
                ('current_storage_mb', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_subscription',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('deployment_mode', models.CharField(default='CLOUD', max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('version', models.CharField(max_length=50)),
                ('health_status', models.CharField(default='HEALTHY', max_length=50)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_deployment',
            },
        ),
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('backup_status', models.CharField(default='PENDING', max_length=50)),
                ('encryption_status', models.BooleanField(default=True)),
                ('restore_point_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('last_successful_backup', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenantbackup',
            },
        ),
        migrations.CreateModel(
            name='TenantMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('active_users', models.IntegerField(default=0)),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('api_calls', models.BigIntegerField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('ram_usage_mb', models.FloatField(default=0.0)),
                ('threat_count', models.IntegerField(default=0)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenantmetrics',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_color', models.CharField(default='#000000', max_length=7)),
                ('theme', models.CharField(default='light', max_length=50)),
                ('password_policy', models.JSONField(default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenantsettings',
            },
        ),
        migrations.CreateModel(
            name='TenantMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False means this record has been soft-deleted.', verbose_name='Is Active')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('MEMBER', 'Member')], default='MEMBER', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_tenantmember',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
