from django.db import models
from django.conf import settings
from common.models.base_model import BaseModel
from apps.monitoring.models.events import EventSeverity

class AlertStatus(models.TextChoices):
    NEW = "NEW", "New"
    ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged"
    RESOLVED = "RESOLVED", "Resolved"

class IncidentStatus(models.TextChoices):
    NEW = "NEW", "New"
    ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged"
    ASSIGNED = "ASSIGNED", "Assigned"
    INVESTIGATING = "INVESTIGATING", "Investigating"
    MITIGATED = "MITIGATED", "Mitigated"
    RESOLVED = "RESOLVED", "Resolved"
    CLOSED = "CLOSED", "Closed"


class Alert(BaseModel):
    """
    Generated by SIEM Engine (Detection/Correlation).
    """
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    severity = models.CharField(max_length=20, choices=EventSeverity.choices, default=EventSeverity.LOW)
    status = models.CharField(max_length=20, choices=AlertStatus.choices, default=AlertStatus.NEW)
    
    # Optional relation to the rule that triggered it
    rule_name = models.CharField(max_length=255, blank=True, null=True)
    
    # Store the actual event IDs or payload that caused the alert
    event_data = models.JSONField(default=dict)
    
    tenant_id = models.UUIDField(null=True, blank=True, db_index=True)

    class Meta:
        db_table = "incident_alert"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Alert: {self.title} ({self.get_severity_display()})"


class Incident(BaseModel):
    """
    High-level incident grouping alerts. Lifecycle managed by Incident Manager.
    """
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    severity = models.CharField(max_length=20, choices=EventSeverity.choices, default=EventSeverity.CRITICAL)
    status = models.CharField(max_length=20, choices=IncidentStatus.choices, default=IncidentStatus.NEW)
    
    tenant_id = models.UUIDField(null=True, blank=True, db_index=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="assigned_incidents")
    
    alerts = models.ManyToManyField(Alert, related_name="incidents", blank=True)

    class Meta:
        db_table = "incident_incident"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Incident: {self.title} ({self.get_status_display()})"


class IncidentActivity(BaseModel):
    """
    Audit log for the incident timeline.
    """
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE, related_name="activities")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=255)
    notes = models.TextField(blank=True)

    class Meta:
        db_table = "incident_activity"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.incident.title} - {self.action}"
