# Generated by Django 5.0.6 on 2026-06-27 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFASecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_encrypted', models.TextField(help_text='Fernet-encrypted TOTP secret. Use MFAService.get_decrypted_secret() to read.', verbose_name='Encrypted Secret')),
                ('algorithm', models.CharField(default='SHA1', max_length=16, verbose_name='Algorithm')),
                ('digits', models.PositiveSmallIntegerField(default=6, verbose_name='Digits')),
                ('period', models.PositiveSmallIntegerField(default=30, verbose_name='Period (seconds)')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='False during setup phase. True after user verifies first TOTP code.', verbose_name='Is Active')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when user first verified the TOTP setup.', null=True, verbose_name='Verified At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_secret', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MFA Secret',
                'verbose_name_plural': 'MFA Secrets',
                'db_table': 'iam_mfa_secrets',
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the plain backup code.', max_length=64, verbose_name='Code Hash')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='True once this code has been consumed for login.', verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Backup Code',
                'verbose_name_plural': 'Backup Codes',
                'db_table': 'iam_backup_codes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='idx_bc_user_unused')],
            },
        ),
    ]
